### ISSUE TITLE
Recent Key button fixes

### ISSUE THREAD

**Issue by rTheCat** [almondnguyen/android_OTA#1]
i have solution for recent app key button. 

for fix 

go system/usr/keylayout and edit Generic.kl

Find APP_SWITCH default is key 580 Change it to key 254 and its done

**Comment by almondnguyen** [comment]
I have that entry

key 254 APP_SWITCH

in sec_touchkey.kl

**Comment by rTheCat** [comment]
u need to use key 254 APP_SWITCH for Generic.kl too for fix problem. i changed it and it fix for me

**Comment by OdimorvanJRZZ** [comment]
i install today the ROM and all things works for my G532MT thanks for all from the support for J2 Prime !!!

**Comment by Brasil150** [comment]
Hi @almondnguyen, congratulations on this ROM, it's amazing and I didn't report a problem. I just wanted to know how the rom development is going, I know it's still in alpha but I noticed that on XDA the download version is November 25th but here on Github there's a December 31st version.

I would like to know if you are still developing and what bugs are still happening. In the version I am (November 25th) the battery is really draining very fast, did you fix that?

Great project!(I'm using Google Translator)
