### ISSUE TITLE
Issue with Booting after Power Off on `lineage-14.1-20230707-UNOFFICIAL-grandppltedx.zip`

### ISSUE THREAD

**Issue by lexavey** [almondnguyen/android_OTA#6]
I recently flashed the `lineage-14.1-20230707-UNOFFICIAL-grandppltedx.zip` ROM on my device. The first boot was successful, and the setup process went smoothly. However, I encountered an issue when I attempted to boot the phone after unplugging the battery and then turning it on by pressing the power button. The phone got stuck at the logo screen, and even after waiting for a few hours, it remained stuck.

To resolve the issue, I backed up my data, reflashed the ROM, restored the data, and the phone booted successfully. However, when I powered off the phone by pressing the power button and turned it on again, the same issue occurred - it got stuck at the logo screen. I tried rebooting to TWRP and then selecting the "reboot system" option, which resulted in a successful boot.

I also attempted to address the issue by flashing `no-verity-no-encrypt_ashyx.zip`, but unfortunately, it had no effect on the problem.

Currently, my TWRP version is `TWRP-3.6.1_9-grandpplte-20220313.img`. I have attached the recovery.log, which may be useful in diagnosing the issue.

Please help me identify the cause of this problem and provide any potential solutions. Thank you!
[recovery.log](https://github.com/almondnguyen/android_OTA/files/12233379/recovery.log)

**Comment by almondnguyen** [comment]
Thank you for the detailed response. We already knew that the 0707 release has buggy kernel that "dies" when phone shuts down improperly. The remedy is to reboot to recovery and then reboot to system from there.

For sure fix, please either revert to the 0623 version, or flash 0623's boot image.
